/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_unidad3;

import java.awt.Image;
import java.util.Arrays;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Oscar
 */
public class unidad5y6 extends javax.swing.JFrame {

    public unidad5y6(){
        initComponents();
        setImageLabel(image, "src/Imagenes/capIm.png");
        bg1.add(brb);
        bg1.add(hash);
        bg1.add(pilas);
        bg1.add(secu);
        bg1.add(hash2);
        bg1.add(bina);
        lbl_buscar.setVisible(false);
        campo_buscar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.ButtonGroup();
        bg2 = new javax.swing.ButtonGroup();
        panel = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        brb = new javax.swing.JRadioButton();
        hash = new javax.swing.JRadioButton();
        pilas = new javax.swing.JRadioButton();
        secu = new javax.swing.JRadioButton();
        hash2 = new javax.swing.JRadioButton();
        bina = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lista1 = new javax.swing.JLabel();
        lista = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_buscar = new javax.swing.JLabel();
        campo_buscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(7, 7, 7));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aq.png"))); // NOI18N
        image.setText("jLabel2");
        image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(7, 7, 7));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingresa los elementos que quieras añadir");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 0)));

        jPanel3.setBackground(new java.awt.Color(7, 7, 7));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 0)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        brb.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        brb.setForeground(new java.awt.Color(255, 255, 255));
        brb.setText("Burbuja");
        brb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brbActionPerformed(evt);
            }
        });

        hash.setBackground(new java.awt.Color(7, 7, 7));
        hash.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        hash.setForeground(new java.awt.Color(255, 255, 255));
        hash.setText("Hash");
        hash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hashActionPerformed(evt);
            }
        });

        pilas.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        pilas.setForeground(new java.awt.Color(255, 255, 255));
        pilas.setText("Inserción");
        pilas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilasActionPerformed(evt);
            }
        });

        secu.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        secu.setForeground(new java.awt.Color(255, 255, 255));
        secu.setText("Secuencial");
        secu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secuActionPerformed(evt);
            }
        });

        hash2.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        hash2.setForeground(new java.awt.Color(255, 255, 255));
        hash2.setText("Hash");
        hash2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hash2ActionPerformed(evt);
            }
        });

        bina.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        bina.setForeground(new java.awt.Color(255, 255, 255));
        bina.setText("Binaria");
        bina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binaActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Métodos de búsqueda");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Métodos de ordenamiento");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(secu)
                        .addGap(32, 32, 32)
                        .addComponent(hash2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bina)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(brb)
                        .addGap(45, 45, 45)
                        .addComponent(hash)
                        .addGap(38, 38, 38)
                        .addComponent(pilas)
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilas)
                    .addComponent(hash)
                    .addComponent(brb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bina)
                    .addComponent(hash2)
                    .addComponent(secu))
                .addGap(20, 20, 20))
        );

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lista1.setBackground(new java.awt.Color(255, 255, 255));
        lista1.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 14)); // NOI18N
        lista1.setForeground(new java.awt.Color(255, 255, 255));
        lista1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lista1.setText("Mensaje");
        lista1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lista.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 14)); // NOI18N
        lista.setForeground(new java.awt.Color(255, 255, 255));
        lista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lista.setText("Aquí se mostrará la cadena");
        lista.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel4.setText("Métodos de búsqueda");

        lbl_buscar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_buscar.setText("Ingresa el elemento a buscar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lista1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 76, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(163, 163, 163))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(campo_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lbl_buscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(143, 143, 143)
                    .addComponent(jLabel4)
                    .addContainerGap(143, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lista1)
                .addGap(18, 18, 18)
                .addComponent(lista)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(188, 188, 188)
                    .addComponent(jLabel4)
                    .addContainerGap(189, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brbActionPerformed
        lbl_buscar.setVisible(false);
        campo_buscar.setVisible(false);
    }//GEN-LAST:event_brbActionPerformed

    private void hashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hashActionPerformed
        lbl_buscar.setVisible(false);
        campo_buscar.setVisible(false);
    }//GEN-LAST:event_hashActionPerformed

    private void pilasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilasActionPerformed
        lbl_buscar.setVisible(false);
        campo_buscar.setVisible(false);
    }//GEN-LAST:event_pilasActionPerformed

    private void secuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secuActionPerformed
        lbl_buscar.setVisible(true);
        campo_buscar.setVisible(true);
    }//GEN-LAST:event_secuActionPerformed

    private void hash2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hash2ActionPerformed
        lbl_buscar.setVisible(true);
        campo_buscar.setVisible(true);
    }//GEN-LAST:event_hash2ActionPerformed

    private void binaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binaActionPerformed
        lbl_buscar.setVisible(true);
        campo_buscar.setVisible(true);
    }//GEN-LAST:event_binaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (brb.isSelected()) {
            int aux;
            String arreglo[] = campo.getText().split(" ");
            int arreglo2[] = new int[arreglo.length];
            for (int i = 0; i < arreglo.length; i++) {
                arreglo2[i] = Integer.parseInt(arreglo[i]);
            }
            for (int i = 0; i < arreglo2.length - 1; i++) {
                for (int j = 0; j < arreglo2.length - i - 1; j++) {
                    if (arreglo2[j + 1] < arreglo2[j]) {
                        aux = arreglo2[j + 1];
                        arreglo2[j + 1] = arreglo2[j];
                        arreglo2[j] = aux;
                    }
                }
            }
            lista1.setText("Los elementos ordenados:");
            lista.setText(Arrays.toString(arreglo2));
        }
        if (hash.isSelected()) {
            String guardar[] = campo.getText().split(" ");
            int arreglo2[] = new int[guardar.length];
            for (int i = 0; i < guardar.length; i++) {
                arreglo2[i] = Integer.parseInt(guardar[i]);
            }
            int arreglo[] = new int[arreglo2.length];

            int i, c = 0, c2 = 0;
            while (c < arreglo.length) {
                i = arreglo2[c] % (arreglo.length);
                if (arreglo[i] != 0) {
                    do {
                        i++;
                        if (i == arreglo.length) {
                            i = 0;
                        }
                        c2++;
                    } while (arreglo[i] != 0 && c2 <= arreglo.length + 1);
                }
                arreglo[i] = arreglo2[c];
                c++;
            }
            lista1.setText("Los elementos ordenados:");
            lista.setText(Arrays.toString(arreglo));
        }
        if (secu.isSelected()) {

            String arreglo[] = campo.getText().split(" ");

            lista.setText(Arrays.toString(arreglo));
            String elemento = campo_buscar.getText();
            for (int i = 0; i < arreglo.length; i++) {
                if (elemento.equals(arreglo[i])) {
                    lista1.setText("El elemento esta en la posicion " + i);
                    break;
                }
                if (i == arreglo.length - 1) {
                    lista1.setText("No se encontro elemento solicitado");
                }
            }

        }
        if (hash2.isSelected()) {
            String guardar[] = campo.getText().split(" ");
            int arreglo2[] = new int[guardar.length];
            for (int i = 0; i < guardar.length; i++) {
                arreglo2[i] = Integer.parseInt(guardar[i]);
            }
            int arreglo[] = new int[arreglo2.length];
            int ele = Integer.parseInt(campo_buscar.getText());
            int i, c = 0, c2 = 0;
            while (c < arreglo.length) {
                i = arreglo2[c] % (arreglo.length);
                if (arreglo[i] != 0) {
                    do {
                        i++;
                        if (i == arreglo.length) {
                            i = 0;
                        }
                        c2++;
                    } while (arreglo[i] != 0 && c2 <= arreglo.length + 1);
                }
                if (arreglo2[c] == ele) {
                    lista1.setText("La clave del elemento buscado es: " + i);
                }
                arreglo[i] = arreglo2[c];
                c++;
            }
            lista.setText(Arrays.toString(arreglo));
        }
        if (bina.isSelected()) {
            int aux;
            String arreglo[] = campo.getText().split(" ");
            int arreglo2[] = new int[arreglo.length];
            for (int i = 0; i < arreglo.length; i++) {
                arreglo2[i] = Integer.parseInt(arreglo[i]);
            }
            for (int i = 0; i < arreglo2.length - 1; i++) {
                for (int j = 0; j < arreglo2.length - i - 1; j++) {
                    if (arreglo2[j + 1] < arreglo2[j]) {
                        aux = arreglo2[j + 1];
                        arreglo2[j + 1] = arreglo2[j];
                        arreglo2[j] = aux;
                    }
                }
            }
            lista.setText(Arrays.toString(arreglo2));
            int n = Integer.parseInt(campo_buscar.getText());
            int menor = 0;
            int enmedio;
            int mayor = (arreglo.length) - 1;
            while (menor <= mayor) {
                enmedio = (menor + mayor) / 2;
                if (arreglo2[enmedio] == n) {
                    lista1.setText("Este número está en la posición: " + enmedio);
                    break;
                } else if (n < arreglo2[enmedio]) {
                    mayor = enmedio - 1;
                } else {
                    menor = enmedio + 1;
                }
            }
        }
        if (pilas.isSelected()) {
            String arreglo[] = campo.getText().split(" ");
            int A[] = new int[arreglo.length];
            for (int i = 0; i < arreglo.length; i++) {
                A[i] = Integer.parseInt(arreglo[i]);
            }
            
            int p, j;
            int aux;
            for (p = 1; p < A.length; p++) { // desde el segundo elemento hasta
                aux = A[p];           // el final, guardamos el elemento y
                j = p - 1;            // empezamos a comprobar con el anterior
                while ((j >= 0) && (aux < A[j])) { // mientras queden posiciones y el                                
                    // valor de aux sea menor que los
                    A[j + 1] = A[j];   // de la izquierda, se desplaza a
                    j--;               // la derecha
                }
                A[j + 1] = aux;       // colocamos aux en su sitio
            }
            lista1.setText("Los elementos ordenados:");
            lista.setText(Arrays.toString(A));
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageMouseClicked
        interfaz v = new interfaz();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_imageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(unidad5y6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(unidad5y6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(unidad5y6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(unidad5y6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new unidad5y6().setVisible(true);
            }
        });
    }

    private void setImageLabel(JLabel label, String ruta) {
        ImageIcon image = new ImageIcon(ruta);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_DEFAULT));
        label.setIcon(icon);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg1;
    private javax.swing.ButtonGroup bg2;
    private javax.swing.JRadioButton bina;
    private javax.swing.JRadioButton brb;
    private javax.swing.JTextField campo;
    private javax.swing.JTextField campo_buscar;
    private javax.swing.JRadioButton hash;
    private javax.swing.JRadioButton hash2;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_buscar;
    private javax.swing.JLabel lista;
    private javax.swing.JLabel lista1;
    private javax.swing.JPanel panel;
    private javax.swing.JRadioButton pilas;
    private javax.swing.JRadioButton secu;
    // End of variables declaration//GEN-END:variables
}
